# Generated by Django 3.1 on 2020-08-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200821_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shippable',
            field=models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Not Digital', 'Not Digital')], max_length=200, null=True),
        ),
    ]
